HADOOP_PREFIX=/usr
HADOOP_COMMON_HOME=/usr
HADOOP_COMMON_DIR=share/java/hadoop-common
HADOOP_COMMON_LIB_JARS_DIR=share/java
HADOOP_COMMON_LIB_NATIVE_DIR=lib
HADOOP_CONF_DIR=/etc/hadoop
HADOOP_LIBEXEC_DIR=/usr/libexec

HADOOP_HDFS_HOME=$HADOOP_PREFIX
HDFS_DIR=share/java/hadoop-hdfs
HDFS_LIB_JARS_DIR=share/java

HADOOP_YARN_HOME=$HADOOP_PREFIX
YARN_DIR=share/java/hadoop-yard
YARN_LIB_JARS_DIR=share/java

HADOOP_MAPRED_HOME=$HADOOP_PREFIX
MAPRED_DIR=share/java/hadoop-mapreduce
MAPRED_LIB_JARS_DIR=share/java
